#!/bin/bash

wait_for_db() {
  until psql -h db -U postgres -d escola-caes-guia -c '\q' 2>/dev/null; do
    echo "Aguardando o banco de dados estar pronto..."
    sleep 2
  done
  echo "Banco de dados está pronto. Iniciando o servidor..."
}

# Aguarde até que o banco de dados esteja pronto
wait_for_db

cd /caes-guia/app/

./gradlew bootRun
echo 'Para acessar o sistema entre em http://localhost:8080/login'
echo 'Login: admin@example.com'
echo 'Senha: senha123'
